In [1]:
import pandas as pd
import numpy as np
import warnings as ws
ws.filterwarnings('ignore')

In [ ]:
# Overall Step in dataScience
# 1. Read the CSV File
# 2. Split Quan and Quali
# 3. Find out missing value and replace the values
# 4. Create custom dataFrame with required columns like "Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%","Max", "IQR", "1.5Rule","Lesser","Greater","Min","Max","Skew","Kurtosis",'Var', 'StdVar'
# 5. Calculate each value for columns
# 6. Find outliers and replace outliers

In [2]:
dataset= pd.read_csv('Placement.csv')
from UnivariateLib import Univariate
quan, quali = Univariate.fnQuanQuali(dataset)
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [3]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [4]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%","Max", "IQR", "1.5Rule","Lesser","Greater","Min","Max","Skew","Kurtosis",'Var', 'StdVar'], columns=quan)
descriptive

         sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean       NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode       NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q1:25%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q2:50%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q3:75%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Max        NaN   NaN   NaN      NaN     NaN   NaN    NaN
IQR        NaN   NaN   NaN      NaN     NaN   NaN    NaN
1.5Rule    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Lesser     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Greater    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Min        NaN   NaN   NaN      NaN     NaN   NaN    NaN
Max        NaN   NaN   NaN      NaN     NaN   NaN    NaN
Skew       NaN   NaN   NaN      NaN     NaN   NaN    NaN
Kurtosis   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Var        NaN   NaN   NaN      NaN     NaN   NaN    NaN
StdVar     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [5]:
from UnivariateLib import Univariate
descriptive = Univariate.fnCentralDedency(quan, dataset)

In [6]:
lesser =[]
greater =[]
from UnivariateLib import Univariate
lesser, greater= Univariate.fnfindOutlier(quan, descriptive);

In [7]:
lesser

['hsc_p']

In [8]:
greater

['hsc_p', 'degree_p', 'salary']

In [9]:
from UnivariateLib import Univariate
dataset= Univariate.fnReplaceOutlier(lesser, greater, dataset,descriptive)

In [10]:
lesser

['hsc_p']

In [11]:
greater

['hsc_p', 'degree_p', 'salary']

In [12]:
from UnivariateLib import Univariate
descriptive = Univariate.fnCentralDedency(quan, dataset)

In [13]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
Skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
Kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837
Var,3870.0,117.228377,112.063731,53.60471,176.251018,34.028376,2944596800.882517
StdVar,62.209324,10.827205,10.586016,7.321524,13.275956,5.833385,54264.139179

In [16]:
lesser =[]
greater =[]
from UnivariateLib import Univariate
lesser, greater= Univariate.fnfindOutlier(quan, descriptive);

In [17]:
lesser

[]

In [18]:
greater

[]