In [1]:
import pandas as pd
import warnings as ws
ws.filterwarnings('ignore')

In [2]:
dataset= pd.read_csv('Placement.csv')
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
from UnivariateLib import Univariate
quan, quali = Univariate.fnQuanQuali(dataset)
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [4]:
quali

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

# Central Dedency

In [5]:
dataset['ssc_p'].mean()

np.float64(67.30339534883721)

In [6]:
dataset['ssc_p'].median()

67.0

In [7]:
dataset['ssc_p'].mode()[0]

np.float64(62.0)

In [18]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [35]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%","99%", "Max"], columns=quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q1:25%   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q2:50%   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q3:75%   NaN   NaN   NaN      NaN     NaN   NaN    NaN
99%      NaN   NaN   NaN      NaN     NaN   NaN    NaN
Max      NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [10]:
from UnivariateLib import Univariate
descriptive = Univariate.fnCentralDedency(quan, descriptive, dataset)
descriptive

        sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean    108.0   NaN   NaN      NaN     NaN   NaN    NaN
Median  108.0   NaN   NaN      NaN     NaN   NaN    NaN
Mode        1   NaN   NaN      NaN     NaN   NaN    NaN

In [23]:
dataset.describe()[colName]["max"]

np.float64(940000.0)

In [37]:
for colName in quan:
             descriptive[colName]["Mean"]= dataset[colName].mean()
             descriptive[colName]["Median"]=  dataset[colName].median()
             descriptive[colName]["Mode"]=  dataset[colName].mode()[0]
             descriptive[colName]["Q1:25%"]=  dataset.describe()[colName]["25%"]
             descriptive[colName]["Q2:50%"]= dataset.describe()[colName]["50%"]
             descriptive[colName]["Q3:75%"]= dataset.describe()[colName]["75%"]
             descriptive[colName]["99%"]= np.percentile(dataset[colName],99) 
             descriptive[colName]["Max"]=  dataset.describe()[colName]["max"]
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Max,215.0,89.4,97.7,91.0,98.0,77.89,940000.0

In [12]:
import numpy as np

In [15]:
np.percentile(dataset['ssc_p'],35)

np.float64(63.0)