In [1]:
import pandas as pd
dataset= pd.read_csv("Preplacement.csv")

In [2]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,0.0

In [3]:
from scipy.stats import ttest_ind
male= dataset[dataset["ssc_b"]=='Others']["salary"]
female=dataset[dataset["ssc_b"]=='Central']["salary"]
ttest_ind(male, female)

TtestResult(statistic=np.float64(0.6182213205902315), pvalue=np.float64(0.5370899470596882), df=np.float64(213.0))

In [4]:
# statistic = 0.6182213205902315, so male is lower
# pvalue = 0.5370899470596882 p < 0.05 → Significant difference
# df - degree of freedon - sample size = df ≈ n₁ + n₂ − 2 = df = 100 + 115 - 2 = 213
# Hypothesis Test
# p <0.05 - 0.5370899470596882 <0.05 = Reject  Null Hypothesis = So we have significant changes between SSC with other and SSC with Central board of salary.

In [10]:
import scipy.stats as stats
stats.f_oneway(
    dataset[dataset['degree_t']=='Sci&Tech']['mba_p'],
    dataset[dataset['degree_t']=='Comm&Mgmt']['mba_p']
)

F_onewayResult(statistic=np.float64(3.180971794904606), pvalue=np.float64(0.07600176846809209))

In [ ]:
# Analysis of variance - One way
# pvalue -0.07600176846809209
# p<0.05 =  0.07600176846809209 > 0.05 = fail to reject null hypothesis - there is no significant variance.

In [ ]:
#Does Gender and Work Experience affect MBA Percentage?
#mba_p -  Dependent Variable 
# Factor 1 - gender
# Factor 2 - work experiene

In [11]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

# ols - Ordinary Least Squares
# It creates a linear regression model, which is also used internally to perform ANOVA.
# 'mba_p ~ C(gender) + C(workex) + C(gender):C(workex)' means Dependent Variable ~ Independent Variables
# C(gender) - statsmodels that gender is a categorical variable. Instead of treating values as numbers, it treats them as groups.
# C(gender) + C(workex) - Include both main effects in the model.
# C(gender):C(workex) - : means interaction effect.
#  Instead of testing gender and work experience separately, it asks, Does the effect of gender depend on work experience?
# .fit() - Calculate Regression coefficients Residuals (errors), Sum of Squares (SS), Mean Squares (MS), F-statistics Everything needed for the ANOVA table

model = ols(
    'mba_p ~ C(gender) + C(workex) + C(gender):C(workex)',
    data=dataset
).fit()

# anova_lm-  ANOVA for Linear Models.
# Calculate Sum of Squares (SS), Degrees of Freedom (df), Mean Square (MS), F-statistic p-value

sm.stats.anova_lm(model, typ=2)

                          sum_sq     df          F    PR(>F)
C(gender)             727.406635    1.0  24.182942  0.000002
C(workex)             277.216606    1.0   9.216184  0.002701
C(gender):C(workex)     0.408011    1.0   0.013564  0.907393
Residual             6346.738197  211.0        NaN       NaN

In [ ]:
# PR(>F) - P values
# C(gender) - 0.000002 <0.05 - There is significant changes
# C(workex) - 0.002701 <0.05 - There is significant changes
# C(gender):C(workex) - 0.907393 > 0.05  - There is no significant changes

In [ ]:
#Does Work Experience and Specialisation affect Salary?

In [12]:
model = ols(
    'salary ~ C(workex) + C(specialisation) + C(workex):C(specialisation)',
    data=dataset
).fit()

sm.stats.anova_lm(model, typ=2)

                                   sum_sq     df          F    PR(>F)
C(workex)                    2.990060e+11    1.0  15.169717  0.000132
C(specialisation)            2.444588e+11    1.0  12.402328  0.000525
C(workex):C(specialisation)  4.320810e+09    1.0   0.219211  0.640125
Residual                     4.158961e+12  211.0        NaN       NaN

In [ ]:
# PR(>F) - P values
# C(workex) - 0.000132 <0.05 - There is significant changes
# C(specialisation) - 0.000525 <0.05 - There is significant changes
# C(workex):C(specialisation) - 0.640125 > 0.05  - There is no significant changes